Stats wired
NullDefault/Volog pull request #41
Opened 2020-11-22 19:21 UTC by malminawi

What I did:
I merged master with a new branch.
I copied the code I did into this branch, to resolve conflict and refactoring issues. 

* Student can edit the hour request if it is being declined by the mentor.
* In the mentor page, the mentor can see a stats bar of each student, as well as for the group as a whole. I also fixed a small bug, in the cards, it was returning the index of the activity category. 
* In the faculty page, the faculty can see a stats bar for each student as well as for each group. 
* I have also wired up the stats tab in the faculty page

2020-11-22 19:29 UTC, malminawi commented on api/views/mentor_views.py
> +        print(self.request.user.mentor_set.first())
this?

2020-11-22 19:33 UTC, NullDefault requested changes
delete all the console logs and its ready for merging

2020-11-22 19:33 UTC, NullDefault commented on api/views/mentor_views.py
> +        print(self.request.query_params)
dont forget to comment / delete these out cause they flood the console logs

2020-11-22 19:33 UTC, NullDefault commented on api/views/mentor_views.py
> +        print(self.request.user.mentor_set.first())
same

2020-11-22 19:33 UTC, NullDefault commented on frontend/src/components/display/cards/studentCard.js
> +        console.log('PROPS', this.props);
remove console logs

2020-11-22 19:33 UTC, NullDefault commented on frontend/src/components/display/cards/studentCard.js
> +        if (prevProps != this.props) {
js comparison syntax should be 3 symbol long (!== instead of !=)

2020-11-22 19:33 UTC, NullDefault commented on frontend/src/components/modals/reportHours.js
> +        console.log('props', this.props)
console log

2020-11-22 19:33 UTC, NullDefault commented on frontend/src/components/pages/faculty/stats/Stats.js
> +        console.log(this.state.chartData)
logs

2020-11-22 19:33 UTC, NullDefault commented on frontend/src/components/pages/hourList.js
> +                console.log('Hour data', data);
console log

2020-11-22 19:33 UTC, NullDefault commented on frontend/src/components/pages/mentor/mentorsIndex.js
> +                            {console.log(data)}
logs

2020-11-22 19:33 UTC, NullDefault commented on frontend/src/functions/services/api/hours_request/stats.js
> +        }).catch(err => console.log(err))
this is the kind of console log you should leave -> it only happens when an error occurred

2020-11-22 19:33 UTC, NullDefault commented on frontend/src/functions/services/api/student_requests/getHoursForStudent.js
> +            console.log('results', results)
logs

2020-11-24 05:32 UTC, malminawi commented on api/views/mentor_views.py
> +        print(self.request.query_params)
Done

2020-11-24 16:36 UTC, NullDefault approved these changes

2020-11-26 18:00 UTC, merged